# Generated by Django 3.1.7 on 2021-04-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(to='main_app.Tool'),
        ),
    ]
